name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: build
        uses: addnab/docker-run-action@v3
        with:
          image: jeffersonlab/clas12software:production
          shell: tcsh
          options: '-v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/work -w /work'
          run: |
            source .github/load-modules.csh
            make
      - name: tree installation
        run: |
          for d in bin include lib lib64 share; do
            echo '[+++++] tree $d'
            tree $d
          done
      - name: test
        uses: addnab/docker-run-action@v3
        with:
          image: jeffersonlab/clas12software:production
          shell: tcsh
          options: '-v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/work -w /work'
          run: |
            source .github/load-modules.csh
            bash -c 'source ./env.sh && make -C test all'
