name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: build
        uses: addnab/docker-run-action@v3
        with:
          image: jeffersonlab/clas12software:production
          options: '-v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/work -w /work'
          run: |
            source /etc/profile.d/modules.sh
            module use /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/sw/modulefiles
            module avail --no-pager
            module load root system pymods
            module list --no-pager
            make -j4
            make install
      - name: tree installation
        run: |
          for d in bin include lib lib64 share; do
            echo ""
            echo "[+++++] tree $d"
            tree --noreport $d || true
          done
      - name: test
        uses: addnab/docker-run-action@v3
        with:
          image: jeffersonlab/clas12software:production
          options: '-v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/work -w /work'
          run: |
            source /etc/profile.d/modules.sh
            module use /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/sw/modulefiles
            module load root system
            make -C test all
            ls -lhtr
